ACoreTransmogLocale = {
    TITLE = "Transmogrification",
    SUBTITLE = "Appearance collection",
    PREVIEW = "PREVIEW",
    COLLECTION = "COLLECTION",
    RESET_PREVIEW = "Reset preview",
    SEARCH_HINT = "Search appearances...",
    SELECT_APPEARANCE = "Select an appearance to preview it",
    PREVIEW_LOADING = "Loading item data for preview...",
    PREVIEWING = "Appearance selected. Click Apply to transmogrify.",
    APPLYING = "Applying appearance...",
    TALK_TO_NPC = "Talk to a transmogrifier to open this window.",
    LOADING = "Loading appearances...",
    EMPTY = "No compatible appearances found.",
    APPLY = "Apply",
    REMOVE = "Remove",
    CLOSE = "Close",
    SEARCH = "Search",
    PREVIOUS = "Previous",
    NEXT = "Next",
    PRICE = "Price:",
    PAGE = "Page %d of %d (%d appearances)",
    APPLIED = "Appearance applied.",
    REMOVED = "Transmogrification removed.",
    SLOT_TRANSMOGRIFIED = "Appearance applied",
    ERROR_SESSION = "The transmogrifier session has expired. Talk to the NPC again.",
    ERROR_THROTTLED = "Please wait before trying again.",
    ERROR_DUPLICATE = "This operation has already been processed.",
    ERROR_SEARCH = "The search text is invalid.",
    ERROR_SLOT = "This equipment slot is unavailable.",
    ERROR_EMPTY_SLOT = "Equip an item in this slot first.",
    ERROR_COLLECTION_DISABLED = "The appearance collection is disabled on the server.",
    ERROR_NOT_COLLECTED = "This appearance is not in your collection.",
    ERROR_NOT_TRANSMOGRIFIED = "This item is not transmogrified.",
    ERROR_INVALID_ITEMS = "This appearance cannot be used with the equipped item.",
    ERROR_MONEY = "You do not have enough money.",
    ERROR_TOKENS = "You do not have enough transmog tokens.",
    ERROR_GENERIC = "The operation could not be completed.",
    INCOMPATIBLE = "The server and addon protocol versions are incompatible.",
    SLOT_0 = "Head",
    SLOT_2 = "Shoulders",
    SLOT_3 = "Shirt",
    SLOT_4 = "Chest",
    SLOT_5 = "Waist",
    SLOT_6 = "Legs",
    SLOT_7 = "Feet",
    SLOT_8 = "Wrists",
    SLOT_9 = "Hands",
    SLOT_14 = "Back",
    SLOT_15 = "Main hand",
    SLOT_16 = "Off hand",
    SLOT_17 = "Ranged",
    SLOT_18 = "Tabard",
}

if GetLocale() == "ruRU" then
    local L = ACoreTransmogLocale
    L.TITLE = "Трансмогрификация"
    L.SUBTITLE = "Коллекция обликов"
    L.PREVIEW = "ПРЕДПРОСМОТР"
    L.COLLECTION = "КОЛЛЕКЦИЯ"
    L.RESET_PREVIEW = "Сбросить примерку"
    L.SEARCH_HINT = "Поиск обликов..."
    L.SELECT_APPEARANCE = "Выберите облик для предпросмотра"
    L.PREVIEW_LOADING = "Загрузка данных предмета для предпросмотра..."
    L.PREVIEWING = "Облик выбран. Нажмите «Применить»."
    L.APPLYING = "Применение облика..."
    L.TALK_TO_NPC = "Поговорите с NPC-трансмогрификатором, чтобы открыть это окно."
    L.LOADING = "Загрузка обликов..."
    L.EMPTY = "Подходящие облики не найдены."
    L.APPLY = "Применить"
    L.REMOVE = "Снять"
    L.CLOSE = "Закрыть"
    L.SEARCH = "Поиск"
    L.PREVIOUS = "Назад"
    L.NEXT = "Далее"
    L.PRICE = "Стоимость:"
    L.PAGE = "Страница %d из %d (обликов: %d)"
    L.APPLIED = "Облик применён."
    L.REMOVED = "Трансмогрификация снята."
    L.SLOT_TRANSMOGRIFIED = "Облик применён"
    L.ERROR_SESSION = "Сессия истекла. Снова поговорите с NPC."
    L.ERROR_THROTTLED = "Подождите перед следующим запросом."
    L.ERROR_DUPLICATE = "Эта операция уже была обработана."
    L.ERROR_SEARCH = "Некорректный текст поиска."
    L.ERROR_SLOT = "Эта ячейка экипировки недоступна."
    L.ERROR_EMPTY_SLOT = "Сначала наденьте предмет в эту ячейку."
    L.ERROR_COLLECTION_DISABLED = "Коллекция обликов отключена на сервере."
    L.ERROR_NOT_COLLECTED = "Этого облика нет в вашей коллекции."
    L.ERROR_NOT_TRANSMOGRIFIED = "На предмете нет трансмогрификации."
    L.ERROR_INVALID_ITEMS = "Этот облик нельзя применить к надетому предмету."
    L.ERROR_MONEY = "Недостаточно денег."
    L.ERROR_TOKENS = "Недостаточно жетонов трансмогрификации."
    L.ERROR_GENERIC = "Не удалось выполнить операцию."
    L.INCOMPATIBLE = "Версии протокола сервера и аддона несовместимы."
    L.SLOT_0 = "Голова"
    L.SLOT_2 = "Плечи"
    L.SLOT_3 = "Рубашка"
    L.SLOT_4 = "Грудь"
    L.SLOT_5 = "Пояс"
    L.SLOT_6 = "Ноги"
    L.SLOT_7 = "Ступни"
    L.SLOT_8 = "Запястья"
    L.SLOT_9 = "Кисти рук"
    L.SLOT_14 = "Спина"
    L.SLOT_15 = "Правая рука"
    L.SLOT_16 = "Левая рука"
    L.SLOT_17 = "Дальний бой"
    L.SLOT_18 = "Гербовая накидка"
end
