ACoreTransmogLocale = {
    TITLE = "Transmogrification",
    SUBTITLE = "Appearance collection",
    PREVIEW = "PREVIEW",
    COLLECTION = "COLLECTION",
    RESET_PREVIEW = "Cancel changes",
    RESET_ALL = "Remove all",
    RESET_ALL_CONFIRM = "Remove all transmogrification appearances from your equipped items?",
    RESET_ALL_SUCCESS = "All transmogrification appearances removed.",
    REMOVING_ALL = "Removing all appearances...",
    SEARCH_HINT = "Search appearances...",
    SELECT_APPEARANCE = "Select an appearance to preview it",
    PREVIEW_LOADING = "Loading item data for preview...",
    PREVIEWING = "Appearance selected.",
    DRAFT_READY = "%d appearance changes in the outfit.",
    APPLYING = "Applying appearance...",
    APPLYING_OUTFIT = "Applying outfit...",
    TALK_TO_NPC = "Talk to a transmogrifier to open this window.",
    LOADING = "Loading appearances...",
    EMPTY = "No compatible appearances found.",
    APPLY = "Apply outfit",
    REMOVE = "Remove",
    OUTFITS = "Outfits",
    OUTFITS_TITLE = "SAVED OUTFITS",
    SET_NAME_HINT = "Outfit name",
    SAVE_SET = "Save current",
    LOAD_SET = "Load",
    RENAME_SET = "Rename",
    DELETE_SET = "Delete",
    DELETE_SET_CONFIRM = "Delete the saved outfit |cffffd36b%s|r?",
    SETS_EMPTY = "No saved outfits",
    SETS_COUNT = "%d of %d outfits",
    SET_SAVED = "Outfit saved.",
    SET_RENAMED = "Outfit renamed.",
    SET_DELETED = "Outfit deleted.",
    SET_UPDATED = "Saved outfits updated.",
    SET_LOADED = "Outfit “%s” loaded into the draft.",
    CLOSE = "Close",
    SEARCH = "Search",
    PREVIOUS = "Previous",
    NEXT = "Next",
    PRICE = "Price:",
    PAGE = "Page %d of %d (%d appearances)",
    APPLIED = "Appearance applied.",
    OUTFIT_APPLIED = "Outfit applied: %d changes.",
    REMOVED = "Transmogrification removed.",
    SLOT_TRANSMOGRIFIED = "Appearance applied",
    SLOT_IN_DRAFT = "Changed in outfit draft",
    SLOT_REMOVAL_DRAFT = "Appearance will be removed",
    OUTFIT_PRICE = "%d changes, total:",
    ERROR_SESSION = "The transmogrifier session has expired. Talk to the NPC again.",
    ERROR_THROTTLED = "Please wait before trying again.",
    ERROR_DUPLICATE = "This operation has already been processed.",
    ERROR_SEARCH = "The search text is invalid.",
    ERROR_SLOT = "This equipment slot is unavailable.",
    ERROR_EMPTY_SLOT = "Equip an item in this slot first.",
    ERROR_COLLECTION_DISABLED = "The appearance collection is disabled on the server.",
    ERROR_NOT_COLLECTED = "This appearance is not in your collection.",
    ERROR_NOT_TRANSMOGRIFIED = "This item is not transmogrified.",
    ERROR_INVALID_ITEMS = "This appearance cannot be used with the equipped item.",
    ERROR_MONEY = "You do not have enough money.",
    ERROR_TOKENS = "You do not have enough transmog tokens.",
    ERROR_GENERIC = "The operation could not be completed.",
    ERROR_SETS_DISABLED = "Saved outfits are disabled on the server.",
    ERROR_SET_NAME = "Enter an outfit name up to 24 characters.",
    ERROR_SET_NAME_EXISTS = "An outfit with that name already exists.",
    ERROR_SET_LIMIT = "The saved outfit limit has been reached.",
    ERROR_SET_NOT_FOUND = "The saved outfit no longer exists.",
    ERROR_EMPTY_SET = "The outfit has no appearances to save.",
    ERROR_SET_TOO_LARGE = "The outfit is too large for one addon message.",
    INCOMPATIBLE = "The server and addon protocol versions are incompatible.",
    SLOT_0 = "Head",
    SLOT_2 = "Shoulders",
    SLOT_3 = "Shirt",
    SLOT_4 = "Chest",
    SLOT_5 = "Waist",
    SLOT_6 = "Legs",
    SLOT_7 = "Feet",
    SLOT_8 = "Wrists",
    SLOT_9 = "Hands",
    SLOT_14 = "Back",
    SLOT_15 = "Main hand",
    SLOT_16 = "Off hand",
    SLOT_17 = "Ranged",
    SLOT_18 = "Tabard",
}

if GetLocale() == "ruRU" then
    local L = ACoreTransmogLocale
    L.TITLE = "Трансмогрификация"
    L.SUBTITLE = "Коллекция обликов"
    L.PREVIEW = "ПРЕДПРОСМОТР"
    L.COLLECTION = "КОЛЛЕКЦИЯ"
    L.RESET_PREVIEW = "Отменить изменения"
    L.RESET_ALL = "Снять все облики"
    L.RESET_ALL_CONFIRM = "Снять все применённые облики с экипированных предметов?"
    L.RESET_ALL_SUCCESS = "Все облики сняты."
    L.REMOVING_ALL = "Снятие всех обликов..."
    L.SEARCH_HINT = "Поиск обликов..."
    L.SELECT_APPEARANCE = "Выберите облик для предпросмотра"
    L.PREVIEW_LOADING = "Загрузка данных предмета для предпросмотра..."
    L.PREVIEWING = "Облик выбран."
    L.DRAFT_READY = "Изменений в образе: %d."
    L.APPLYING = "Применение облика..."
    L.APPLYING_OUTFIT = "Применение образа..."
    L.TALK_TO_NPC = "Поговорите с NPC-трансмогрификатором, чтобы открыть это окно."
    L.LOADING = "Загрузка обликов..."
    L.EMPTY = "Подходящие облики не найдены."
    L.APPLY = "Применить образ"
    L.REMOVE = "Снять"
    L.OUTFITS = "Комплекты"
    L.OUTFITS_TITLE = "СОХРАНЁННЫЕ КОМПЛЕКТЫ"
    L.SET_NAME_HINT = "Название комплекта"
    L.SAVE_SET = "Сохранить текущий"
    L.LOAD_SET = "Загрузить"
    L.RENAME_SET = "Переименовать"
    L.DELETE_SET = "Удалить"
    L.DELETE_SET_CONFIRM = "Удалить сохранённый комплект |cffffd36b%s|r?"
    L.SETS_EMPTY = "Сохранённых комплектов нет"
    L.SETS_COUNT = "Комплектов: %d из %d"
    L.SET_SAVED = "Комплект сохранён."
    L.SET_RENAMED = "Комплект переименован."
    L.SET_DELETED = "Комплект удалён."
    L.SET_UPDATED = "Список комплектов обновлён."
    L.SET_LOADED = "Комплект «%s» загружен в черновик."
    L.CLOSE = "Закрыть"
    L.SEARCH = "Поиск"
    L.PREVIOUS = "Назад"
    L.NEXT = "Далее"
    L.PRICE = "Стоимость:"
    L.PAGE = "Страница %d из %d (обликов: %d)"
    L.APPLIED = "Облик применён."
    L.OUTFIT_APPLIED = "Образ применён: изменений — %d."
    L.REMOVED = "Трансмогрификация снята."
    L.SLOT_TRANSMOGRIFIED = "Облик применён"
    L.SLOT_IN_DRAFT = "Изменено в черновике образа"
    L.SLOT_REMOVAL_DRAFT = "Облик будет снят"
    L.OUTFIT_PRICE = "Изменений: %d, итого:"
    L.ERROR_SESSION = "Сессия истекла. Снова поговорите с NPC."
    L.ERROR_THROTTLED = "Подождите перед следующим запросом."
    L.ERROR_DUPLICATE = "Эта операция уже была обработана."
    L.ERROR_SEARCH = "Некорректный текст поиска."
    L.ERROR_SLOT = "Эта ячейка экипировки недоступна."
    L.ERROR_EMPTY_SLOT = "Сначала наденьте предмет в эту ячейку."
    L.ERROR_COLLECTION_DISABLED = "Коллекция обликов отключена на сервере."
    L.ERROR_NOT_COLLECTED = "Этого облика нет в вашей коллекции."
    L.ERROR_NOT_TRANSMOGRIFIED = "На предмете нет трансмогрификации."
    L.ERROR_INVALID_ITEMS = "Этот облик нельзя применить к надетому предмету."
    L.ERROR_MONEY = "Недостаточно денег."
    L.ERROR_TOKENS = "Недостаточно жетонов трансмогрификации."
    L.ERROR_GENERIC = "Не удалось выполнить операцию."
    L.ERROR_SETS_DISABLED = "Сохранённые комплекты отключены на сервере."
    L.ERROR_SET_NAME = "Введите название комплекта длиной до 24 символов."
    L.ERROR_SET_NAME_EXISTS = "Комплект с таким названием уже существует."
    L.ERROR_SET_LIMIT = "Достигнут лимит сохранённых комплектов."
    L.ERROR_SET_NOT_FOUND = "Сохранённый комплект больше не существует."
    L.ERROR_EMPTY_SET = "В комплекте нет обликов для сохранения."
    L.ERROR_SET_TOO_LARGE = "Комплект слишком большой для одного сообщения аддона."
    L.INCOMPATIBLE = "Версии протокола сервера и аддона несовместимы."
    L.SLOT_0 = "Голова"
    L.SLOT_2 = "Плечи"
    L.SLOT_3 = "Рубашка"
    L.SLOT_4 = "Грудь"
    L.SLOT_5 = "Пояс"
    L.SLOT_6 = "Ноги"
    L.SLOT_7 = "Ступни"
    L.SLOT_8 = "Запястья"
    L.SLOT_9 = "Кисти рук"
    L.SLOT_14 = "Спина"
    L.SLOT_15 = "Правая рука"
    L.SLOT_16 = "Левая рука"
    L.SLOT_17 = "Дальний бой"
    L.SLOT_18 = "Гербовая накидка"
end
